function courseArt(title, accent, icon) {
  const icons = {
    monitor: '<rect x="92" y="58" width="136" height="86" rx="10" fill="#ffffff" opacity=".94"/><rect x="110" y="76" width="100" height="14" rx="7" fill="#dbe8e2"/><rect x="110" y="100" width="72" height="12" rx="6" fill="#84b8ad"/><path d="M144 144h32l8 22h-48l8-22Z" fill="#244247"/><rect x="120" y="166" width="80" height="10" rx="5" fill="#244247"/>',
    keyboard: '<rect x="70" y="78" width="180" height="90" rx="14" fill="#ffffff" opacity=".94"/><g fill="#dbe8e2"><rect x="92" y="100" width="26" height="16" rx="5"/><rect x="126" y="100" width="26" height="16" rx="5"/><rect x="160" y="100" width="26" height="16" rx="5"/><rect x="194" y="100" width="26" height="16" rx="5"/><rect x="92" y="126" width="42" height="16" rx="5"/><rect x="142" y="126" width="76" height="16" rx="5"/></g>',
    folder: '<path d="M76 88h74l18 20h78v72H76V88Z" fill="#ffffff" opacity=".94"/><rect x="92" y="122" width="112" height="12" rx="6" fill="#84b8ad"/><rect x="92" y="146" width="72" height="12" rx="6" fill="#dbe8e2"/>',
    phone: '<rect x="116" y="44" width="88" height="152" rx="22" fill="#ffffff" opacity=".94"/><rect x="132" y="72" width="56" height="78" rx="10" fill="#dbe8e2"/><circle cx="160" cy="174" r="8" fill="#244247"/>',
    chat: '<rect x="76" y="70" width="130" height="76" rx="18" fill="#ffffff" opacity=".94"/><path d="M106 146l-18 26 42-26h76" fill="#ffffff" opacity=".94"/><rect x="104" y="94" width="76" height="10" rx="5" fill="#84b8ad"/><rect x="104" y="116" width="52" height="10" rx="5" fill="#dbe8e2"/>',
    shield: '<path d="M160 48l80 30v58c0 48-34 78-80 96-46-18-80-48-80-96V78l80-30Z" fill="#ffffff" opacity=".94"/><path d="M132 130l20 20 42-54" fill="none" stroke="#244247" stroke-width="14" stroke-linecap="round" stroke-linejoin="round"/>',
    app: '<rect x="92" y="58" width="136" height="136" rx="24" fill="#ffffff" opacity=".94"/><g fill="#84b8ad"><rect x="118" y="86" width="34" height="34" rx="10"/><rect x="168" y="86" width="34" height="34" rx="10"/><rect x="118" y="136" width="34" height="34" rx="10"/><rect x="168" y="136" width="34" height="34" rx="10"/></g>',
    bank: '<rect x="74" y="92" width="172" height="86" rx="10" fill="#ffffff" opacity=".94"/><path d="M86 90l74-42 74 42H86Z" fill="#ffffff" opacity=".94"/><g fill="#244247"><rect x="100" y="108" width="18" height="48" rx="4"/><rect x="136" y="108" width="18" height="48" rx="4"/><rect x="172" y="108" width="18" height="48" rx="4"/><rect x="208" y="108" width="18" height="48" rx="4"/></g>',
    cart: '<circle cx="128" cy="170" r="12" fill="#244247"/><circle cx="204" cy="170" r="12" fill="#244247"/><path d="M84 72h28l18 72h86l20-50H126" fill="none" stroke="#ffffff" stroke-width="16" stroke-linecap="round" stroke-linejoin="round" opacity=".94"/>',
    map: '<path d="M102 70l54-20 62 20v116l-62-20-54 20-42-18V52l42 18Z" fill="#ffffff" opacity=".94"/><path d="M156 50v116M102 70v116" stroke="#244247" stroke-width="8" opacity=".7"/>'
  };

  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 220">
      <rect width="320" height="220" fill="${accent}"/>
      <circle cx="260" cy="46" r="52" fill="#ffffff" opacity=".18"/>
      <circle cx="42" cy="190" r="78" fill="#ffffff" opacity=".12"/>
      ${icons[icon]}
      <text x="26" y="198" fill="#ffffff" font-family="Arial, sans-serif" font-size="18" font-weight="700">${title}</text>
    </svg>
  `;

  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
}

function genericPcArt() {
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 420">
      <rect width="640" height="420" fill="#e7efe8"/>
      <circle cx="520" cy="78" r="82" fill="#1f7a76" opacity=".14"/>
      <circle cx="92" cy="342" r="118" fill="#d79a2b" opacity=".16"/>
      <rect x="130" y="82" width="380" height="232" rx="24" fill="#244247"/>
      <rect x="156" y="108" width="328" height="178" rx="14" fill="#ffffff"/>
      <rect x="186" y="140" width="214" height="18" rx="9" fill="#dbe8e2"/>
      <rect x="186" y="178" width="268" height="16" rx="8" fill="#84b8ad"/>
      <rect x="186" y="214" width="178" height="16" rx="8" fill="#dbe8e2"/>
      <path d="M294 314h52l16 50h-84l16-50Z" fill="#244247"/>
      <rect x="236" y="354" width="168" height="26" rx="13" fill="#244247"/>
      <rect x="190" y="386" width="260" height="16" rx="8" fill="#ffffff" opacity=".82"/>
    </svg>
  `;

  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
}

function topic(title, text, objective, steps, practice, warning, showImage = false) {
  return [title, text, showImage, { objective, steps, practice, warning }];
}

const introTopics = {
  basico: topic("O que é um computador?", "Computador é um aparelho usado para escrever textos, acessar a internet, guardar arquivos, ver fotos, estudar, trabalhar e usar programas. Ele pode ser de mesa, com monitor e gabinete, ou um notebook, que já vem com tela, teclado e bateria.", "Entender para que serve um computador e reconhecer as partes mais importantes antes de usar.", ["Observe se o aparelho é computador de mesa ou notebook.", "Identifique a tela, onde aparecem textos, imagens e janelas.", "Identifique teclado, mouse ou touchpad, usados para controlar o computador.", "Procure botão de ligar, entrada de energia e entrada USB.", "Entenda que programas são ferramentas abertas dentro do computador."], "Explique em voz alta para que serve a tela, o teclado, o mouse e o botão de ligar.", "Não conecte cabos com força e não desligue o computador tirando da tomada sem necessidade.", true),
  celular: topic("O que é um celular smartphone?", "Smartphone é um celular com tela sensível ao toque que permite fazer ligações, mandar mensagens, tirar fotos, acessar a internet, usar aplicativos e guardar informações pessoais.", "Entender o que o celular faz e quais partes aparecem na tela inicial.", ["Veja a tela inicial, onde ficam os ícones dos aplicativos.", "Observe os botões físicos, como volume e ligar/desligar.", "Entenda que aplicativos são ferramentas para tarefas diferentes.", "Veja os símbolos de bateria, sinal, Wi-Fi e notificações.", "Reconheça que o celular guarda dados pessoais e precisa de cuidado."], "Olhe para a tela inicial e encontre telefone, mensagens, câmera e configurações.", "Use senha, digital ou rosto para bloquear o aparelho e proteger suas informações.", true),
  navegadores: topic("O que é um navegador?", "Navegador é o programa usado para abrir sites na internet. Exemplos comuns são Chrome, Edge, Firefox e Safari. É nele que você pesquisa, acessa serviços, lê notícias e entra em páginas importantes.", "Entender que o navegador é a porta de entrada para sites e buscas.", ["Procure o ícone do navegador no computador ou celular.", "Abra o navegador e observe a barra de endereço.", "Entenda que a barra serve para digitar sites ou pesquisas.", "Veja que cada página pode abrir em uma aba.", "Use voltar, avançar e atualizar para controlar a navegação."], "Abra o navegador e localize a barra onde se digita um endereço ou pesquisa.", "Confirme o endereço do site antes de informar senha, CPF ou dados de pagamento.", true),
  arquivos: topic("O que são arquivos e pastas?", "Arquivo é um item guardado no computador ou celular, como foto, documento, PDF, comprovante ou planilha. Pasta é um lugar usado para organizar esses arquivos por assunto.", "Entender a diferença entre arquivo, pasta e local de armazenamento.", ["Veja que uma foto, um PDF e um texto são tipos de arquivo.", "Entenda que pastas agrupam arquivos parecidos.", "Abra Documentos, Downloads ou Imagens.", "Observe nomes, datas e tipos dos arquivos.", "Use nomes claros para encontrar tudo depois."], "Abra uma pasta e escolha três arquivos, dizendo que tipo de informação cada um guarda.", "Não apague arquivos importantes ou de outras pessoas sem confirmar.", true),
  email: topic("O que é e-mail?", "E-mail é um endereço digital usado para enviar e receber mensagens, documentos, comprovantes e avisos. Ele também serve para criar cadastros e recuperar senhas de muitos serviços.", "Entender para que serve uma conta de e-mail e por que ela deve ser protegida.", ["Veja que um endereço de e-mail geralmente tem nome, arroba e domínio.", "Abra a caixa de entrada para ver mensagens recebidas.", "Observe remetente, assunto e data.", "Entenda que anexos são arquivos enviados junto da mensagem.", "Use o e-mail com senha segura."], "Identifique seu endereço de e-mail e encontre a caixa de entrada.", "Não entregue senha ou código de recuperação recebido por e-mail para outra pessoa.", true),
  comunicacao: topic("O que são mensagens digitais?", "Mensagens digitais são textos, áudios, fotos ou chamadas enviados por aplicativos no celular. Elas ajudam a conversar rapidamente com familiares, amigos, grupos e serviços.", "Entender os tipos de mensagem e quando usar cada um.", ["Veja que texto é bom para recados curtos.", "Use áudio quando for difícil digitar.", "Use foto quando precisa mostrar algo.", "Use chamada quando precisa conversar ao vivo.", "Confira sempre a pessoa ou grupo antes de enviar."], "Abra um aplicativo de mensagens e identifique campo de texto, microfone e botão de enviar.", "Não mande senhas, códigos ou documentos em conversas sem necessidade.", true),
  whatsapp: topic("O que é WhatsApp?", "WhatsApp é um aplicativo de mensagens usado para conversar por texto, áudio, foto, ligação e grupos. Como muita gente usa, ele também é alvo comum de golpes.", "Entender para que serve o WhatsApp e quais cuidados básicos ele exige.", ["Abra o WhatsApp e veja a lista de conversas.", "Observe contatos, grupos e números desconhecidos.", "Entenda que conversas podem receber texto, áudio, foto e documentos.", "Veja onde ficam chamadas e configurações.", "Use privacidade e verificação em duas etapas quando possível."], "Abra o WhatsApp e encontre uma conversa individual, um grupo e as configurações.", "Desconfie de números novos pedindo dinheiro ou códigos de confirmação.", true),
  "redes-sociais": topic("O que são redes sociais?", "Redes sociais são aplicativos ou sites onde pessoas publicam textos, fotos, vídeos curtos, comentários e mensagens. Elas servem para acompanhar pessoas e assuntos, mas exigem cuidado com privacidade.", "Entender perfil, publicação, feed, curtida e comentário.", ["Veja que o perfil mostra informações sobre você.", "Entenda que o feed mostra publicações de outras pessoas e páginas.", "Curtida é uma reação rápida a uma publicação.", "Comentário é uma resposta escrita.", "Configurações de privacidade controlam quem vê suas informações."], "Abra uma rede social e identifique perfil, feed, curtida e comentário.", "Evite publicar endereço, documentos, rotina, dados bancários ou informações de crianças.", true),
  fotos: topic("O que são câmera e galeria?", "A câmera serve para tirar fotos e gravar imagens. A galeria é o local onde essas fotos, capturas de tela e imagens recebidas ficam guardadas no celular.", "Entender a diferença entre tirar uma foto e encontrar uma foto já salva.", ["Abra a câmera e veja o botão de tirar foto.", "Tire uma foto simples de teste.", "Abra a galeria ou fotos.", "Encontre a imagem mais recente.", "Observe álbuns, favoritos e lixeira quando existirem."], "Tire uma foto de um objeto e depois encontre essa foto na galeria.", "Não compartilhe fotos de documentos, cartões ou telas de banco sem necessidade.", true),
  seguranca: topic("O que é segurança digital?", "Segurança digital é o conjunto de cuidados para proteger celular, computador, contas, senhas, dinheiro e dados pessoais contra golpes, invasões e enganos.", "Entender por que segurança digital deve vir antes de clicar, pagar ou informar dados.", ["Desconfie de mensagens com pressa, medo ou promessa de prêmio.", "Confira quem enviou antes de responder.", "Não clique em links suspeitos.", "Use senhas fortes e bloqueio de tela.", "Peça ajuda quando envolver dinheiro ou documento."], "Pense em uma mensagem suspeita e identifique quem enviou, o que pediu e se havia urgência.", "Golpistas tentam criar pressa para impedir que você confira com calma.", true),
  senhas: topic("O que são senhas?", "Senha é uma chave secreta usada para entrar em contas, aplicativos e serviços. Ela protege e-mail, redes sociais, banco, gov.br e outros acessos importantes.", "Entender por que senha é pessoal e precisa ser forte.", ["Veja que cada conta importante deve ter uma senha própria.", "Evite datas, nomes e sequências fáceis.", "Use letras, números e símbolos quando possível.", "Guarde em local seguro.", "Nunca envie senha por mensagem."], "Crie uma senha de treino usando palavras, números e símbolo, sem usar dados reais.", "Quem pede sua senha completa geralmente não deveria ter acesso a ela.", true),
  bancos: topic("O que é banco pelo celular?", "Banco pelo celular é o uso do aplicativo oficial do banco para consultar saldo, extrato, Pix, pagamentos, cartões e comprovantes. Ele facilita a vida, mas envolve dinheiro e precisa de atenção.", "Entender o que pode ser feito no app do banco e quais cuidados vêm primeiro.", ["Use apenas o aplicativo oficial instalado pela loja do celular.", "Entre em local privado.", "Confira saldo e extrato sem pressa.", "Revise dados antes de qualquer pagamento.", "Saia ou bloqueie a tela ao terminar."], "Abra o aplicativo do banco apenas para observar a tela inicial, sem fazer transações.", "Banco não pede senha completa, código ou transferência para conta segura por mensagem.", true),
  pix: topic("O que é Pix?", "Pix é uma forma de transferir ou receber dinheiro quase na hora usando chave, QR Code ou dados da conta. Por ser rápido, exige conferência antes de confirmar.", "Entender para que serve o Pix e por que a conferência é essencial.", ["Abra a área Pix no app do banco.", "Veja opções como pagar, receber, chave e QR Code.", "Entenda que chave Pix identifica quem recebe.", "Confira nome, banco e valor antes de confirmar.", "Guarde o comprovante depois."], "Entre na área Pix e observe as opções sem realizar pagamento.", "Pix enviado para pessoa errada pode ser difícil de recuperar.", true),
  "compras-online": topic("O que são compras online?", "Compras online são compras feitas por site ou aplicativo, com pagamento pela internet e entrega em casa ou retirada. Elas exigem cuidado com loja, preço, pagamento e entrega.", "Entender as partes de uma compra online antes de finalizar.", ["Veja nome da loja e endereço do site.", "Leia descrição, preço, frete e prazo.", "Confira avaliações e reclamações.", "Escolha forma de pagamento segura.", "Guarde confirmação e número do pedido."], "Pesquise um produto sem comprar e observe preço, frete, prazo e nome da loja.", "Desconfie de preço muito baixo, Pix para pessoa física desconhecida e links recebidos em grupos.", true),
  govbr: topic("O que é gov.br?", "gov.br é a conta usada para acessar serviços digitais do governo, como documentos, consultas, benefícios, impostos, INSS e outros atendimentos públicos.", "Entender para que serve a conta gov.br e como reconhecer canais oficiais.", ["Acesse apenas site ou aplicativo oficial gov.br.", "Entenda que o CPF identifica a conta.", "Use senha com cuidado.", "Procure serviços dentro do ambiente oficial.", "Guarde protocolos quando fizer solicitações."], "Abra o site oficial gov.br e observe os serviços disponíveis sem informar dados se estiver inseguro.", "Não pague desconhecidos nem clique em links suspeitos para acessar sua conta gov.br.", true),
  documentos: topic("O que são documentos digitais?", "Documentos digitais são arquivos no computador ou celular que representam informações importantes, como PDF, comprovante, boleto, contrato, foto de documento ou arquivo escaneado.", "Entender tipos comuns de documento digital e como guardar com segurança.", ["Veja que PDF é comum para boletos e comprovantes.", "Entenda que foto de documento também contém dados pessoais.", "Guarde documentos em pastas organizadas.", "Use nomes claros para encontrar depois.", "Compartilhe somente com destinatários confiáveis."], "Abra uma pasta de documentos e identifique quais arquivos são PDF, imagem ou comprovante.", "Documentos digitais podem conter CPF, endereço e assinatura. Não envie para desconhecidos.", true),
  mapas: topic("O que são mapas digitais?", "Mapas digitais são aplicativos que mostram ruas, endereços, rotas, distância, tempo de trajeto e locais próximos. Eles ajudam a encontrar caminhos e serviços.", "Entender endereço, rota, localização e tipos de transporte no mapa.", ["Abra o aplicativo de mapas.", "Digite um endereço ou nome de local.", "Veja se cidade e bairro estão corretos.", "Toque em Rotas para ver caminhos.", "Escolha carro, caminhada, transporte público ou aplicativo quando disponível."], "Pesquise um lugar conhecido e veja quanto tempo levaria para chegar.", "Não compartilhe localização com desconhecidos e não use o celular enquanto dirige.", true),
  manutencao: topic("O que é manutenção básica?", "Manutenção básica é o conjunto de cuidados simples para manter computador e celular funcionando melhor, como limpar, liberar espaço, atualizar e reiniciar quando necessário.", "Entender cuidados simples antes de procurar conserto.", ["Mantenha o aparelho limpo e seco.", "Evite deixar armazenamento cheio.", "Reinicie quando algo travar.", "Atualize aplicativos conhecidos.", "Peça ajuda se aparecer erro que você não entende."], "Confira se seu aparelho está com pouco espaço ou muitas notificações de atualização.", "Não aceite suporte remoto de desconhecidos dizendo que vão consertar seu aparelho.", true),
  acessibilidade: topic("O que é acessibilidade digital?", "Acessibilidade digital são ajustes que facilitam o uso do celular e computador, como aumentar letra, mudar brilho, usar legenda, lupa, leitor de tela e volume adequado.", "Entender que o aparelho pode ser adaptado para enxergar, ouvir e usar melhor.", ["Abra configurações do aparelho.", "Procure Tela, Som ou Acessibilidade.", "Veja opções de tamanho da fonte.", "Confira brilho, contraste e volume.", "Teste uma mudança por vez."], "Encontre a área de acessibilidade no seu celular ou computador.", "Algumas opções mudam gestos e sons. Ative uma por vez para não se confundir.", true)
};

function withIntroTopic(slug, topics) {
  if (topics[0]?.[0].toLowerCase().startsWith("o que é")) {
    return topics;
  }

  return introTopics[slug] ? [introTopics[slug], ...topics] : topics;
}

function makeCourse(slug, category, label, title, summary, level, accent, icon, artTitle, topics) {
  const image = courseArt(artTitle, accent, icon);
  const lessonImage = category === "computador"
    ? genericPcArt()
    : courseArt("Celular", "#3b6ea8", "phone");
  return {
    slug,
    category,
    label,
    title,
    summary,
    level,
    image_url: image,
    lesson_image_url: lessonImage,
    card_image_url: image,
    topics: withIntroTopic(slug, topics)
  };
}

const courses = [
  makeCourse("basico", "computador", "Informática básica", "Primeiros passos no computador", "Conheça as partes do computador, a área de trabalho, janelas, mouse e teclado.", "PC", "#1f7a76", "monitor", "Computador", [
    topic("Conheça o computador", "O computador tem partes que trabalham juntas: tela, teclado, mouse, gabinete ou notebook, energia e entradas para acessórios.", "Reconhecer as principais partes do computador.", ["Observe o monitor, que mostra imagens, textos e janelas.", "Localize o gabinete ou notebook, onde ficam os componentes principais.", "Identifique teclado, mouse ou touchpad.", "Procure botão de ligar, entrada USB, fone e carregador.", "Diga o nome de cada parte antes de começar."], "Olhe para o computador e aponte monitor, teclado, mouse, botão de ligar e entrada USB.", "Não force cabos ou conectores. Se não encaixar com facilidade, confira a posição.", true),
    topic("Use mouse e teclado", "Clique, duplo clique, arrastar, rolagem e digitação são movimentos básicos para quase tudo no computador.", "Praticar os comandos mais usados no mouse e no teclado.", ["Mova o mouse devagar e observe a seta na tela.", "Clique uma vez para selecionar um item.", "Dê dois cliques rápidos para abrir programas ou pastas.", "Use a rodinha do mouse para subir e descer.", "Digite uma frase curta e use Backspace para apagar."], "Abra um campo de texto e escreva seu nome, a data e uma frase simples.", "Evite clicar várias vezes seguidas quando o computador estiver lento."),
    topic("Entenda as janelas", "Programas aparecem em janelas. Elas podem ser abertas, minimizadas, aumentadas, movidas e fechadas.", "Controlar janelas sem se perder na tela.", ["Abra um programa simples, como calculadora ou bloco de notas.", "Use o botão de minimizar para esconder a janela.", "Clique no ícone na barra de tarefas para voltar.", "Use maximizar para ocupar a tela toda.", "Feche pelo X quando terminar."], "Abra duas janelas e alterne entre elas pela barra de tarefas.", "Salve documentos antes de fechar uma janela importante.", true),
    topic("Desligue corretamente", "Desligar pelo sistema evita perda de arquivos e problemas na próxima vez que ligar.", "Encerrar o uso do computador com segurança.", ["Feche programas que não estiver usando.", "Salve arquivos abertos.", "Clique no menu iniciar ou botão de energia do sistema.", "Escolha Desligar.", "Aguarde a tela apagar por completo."], "Treine encontrar a opção Desligar sem clicar nela.", "Evite tirar da tomada com o computador ligado, exceto em emergência.")
  ]),
  makeCourse("celular", "celular", "Uso do celular", "Primeiros passos no celular", "Aprenda gestos, tela inicial, notificações, volume, Wi-Fi e cuidados básicos.", "Celular", "#3b6ea8", "phone", "Celular", [
    topic("Conheça a tela inicial", "A tela inicial reúne aplicativos, relógio, notificações e atalhos importantes.", "Encontrar os principais elementos da tela do celular.", ["Desbloqueie o celular com senha, desenho, digital ou rosto.", "Observe os ícones dos aplicativos.", "Deslize para os lados para ver outras telas.", "Puxe de cima para baixo para ver notificações.", "Toque no botão inicial ou gesto de voltar para retornar."], "Localize telefone, mensagens, câmera, configurações e loja de aplicativos.", "Não altere configurações que você não conhece sem anotar o que mudou.", true),
    topic("Use os gestos básicos", "Tocar, segurar, deslizar e ampliar com dois dedos ajudam a navegar em quase todos os aplicativos.", "Praticar gestos comuns do celular.", ["Toque uma vez para abrir ou escolher.", "Toque e segure para ver opções extras.", "Deslize para rolar páginas e listas.", "Use dois dedos para ampliar uma foto ou mapa.", "Use voltar para sair de telas internas."], "Abra uma foto e treine ampliar, diminuir e voltar.", "Se aparecer uma opção de apagar ou comprar, cancele e leia com calma."),
    topic("Conecte no Wi-Fi", "O Wi-Fi permite usar internet sem gastar dados móveis da operadora.", "Entrar em uma rede Wi-Fi conhecida.", ["Abra Configurações.", "Toque em Wi-Fi ou Rede e Internet.", "Escolha a rede correta pelo nome.", "Digite a senha com atenção.", "Veja se apareceu o símbolo de Wi-Fi no topo da tela."], "Conecte-se à rede da sua casa ou de um local de confiança.", "Evite usar Wi-Fi público para banco, compras ou documentos pessoais.", true),
    topic("Atualize com cuidado", "Atualizações corrigem falhas e melhoram aplicativos, mas precisam de bateria e conexão estável.", "Entender quando atualizar aplicativos e sistema.", ["Abra a loja de aplicativos.", "Procure a área de atualizações.", "Atualize aplicativos conhecidos.", "Conecte o carregador se a bateria estiver baixa.", "Leia avisos antes de atualizar o sistema."], "Confira se há atualizações pendentes na loja de aplicativos.", "Não baixe atualizações enviadas por links de mensagem.")
  ]),
  makeCourse("internet", "computador", "Internet básica", "Como usar a internet", "Entenda conexão, navegador, sites, busca e cuidados antes de clicar.", "PC e celular", "#2f5f98", "app", "Internet", [
    topic("O que é internet?", "Internet é uma rede que conecta pessoas, sites, serviços, aplicativos e informações.", "Entender para que a internet serve no dia a dia.", ["Veja se o aparelho está conectado por Wi-Fi, cabo ou dados móveis.", "Abra um navegador ou aplicativo.", "Digite um endereço ou faça uma busca.", "Espere a página carregar.", "Use voltar quando quiser retornar."], "Explique com suas palavras três coisas que você consegue fazer pela internet.", "Nem tudo que aparece na internet é verdadeiro ou seguro.", true),
    topic("Use sites com atenção", "Sites podem informar, vender, atender serviços ou pedir dados. É importante saber onde você está.", "Identificar endereço, título e finalidade de uma página.", ["Observe o nome do site na parte superior.", "Leia o título e veja se combina com o que você procurou.", "Procure menus como início, contato e ajuda.", "Desconfie de páginas com muitos avisos urgentes.", "Feche páginas que pedem instalação inesperada."], "Abra um site conhecido e encontre o endereço, menu e campo de busca.", "Não informe CPF, senha ou cartão em sites que você não conhece."),
    topic("Pesquise melhor", "Uma boa pesquisa usa palavras claras e compara mais de um resultado.", "Fazer buscas simples e escolher resultados confiáveis.", ["Abra o buscador.", "Digite poucas palavras importantes.", "Leia os primeiros resultados antes de clicar.", "Prefira sites oficiais quando o assunto envolver governo, banco ou saúde.", "Compare informações em mais de uma fonte."], "Pesquise o horário de funcionamento de um serviço local e confira em dois lugares.", "Cuidado com anúncios que aparecem antes dos resultados comuns.", true),
    topic("Baixe arquivos com cautela", "Downloads podem trazer documentos úteis, mas também arquivos falsos ou perigosos.", "Baixar apenas quando a origem for confiável.", ["Confira se você realmente precisa baixar.", "Veja o nome do site e do arquivo.", "Prefira PDF, imagem ou documento esperado.", "Evite executáveis desconhecidos.", "Depois de baixar, abra pela pasta Downloads."], "Baixe um PDF de um site confiável e encontre-o em Downloads.", "Nunca instale programas enviados por desconhecidos.")
  ]),
  makeCourse("navegadores", "computador", "Navegador", "Abas, favoritos e histórico", "Aprenda a usar abas, voltar, atualizar, favoritos, downloads e histórico.", "PC e celular", "#5d6f86", "monitor", "Navegador", [
    topic("Abra e feche abas", "Abas permitem deixar mais de uma página aberta no navegador.", "Usar abas sem se confundir.", ["Abra o navegador.", "Clique no sinal de mais para abrir uma nova aba.", "Digite uma busca ou endereço.", "Clique na aba anterior para voltar.", "Feche pelo X da aba quando terminar."], "Abra duas abas: uma com uma busca e outra com um site conhecido.", "Não feche todas as abas antes de terminar uma tarefa importante.", true),
    topic("Use voltar e atualizar", "Voltar retorna para a página anterior. Atualizar carrega a página de novo.", "Navegar entre páginas usando controles básicos.", ["Clique em um resultado de busca.", "Use a seta Voltar para retornar.", "Use Avançar se quiser ir de novo.", "Clique em Atualizar se a página travar.", "Espere o carregamento terminar antes de clicar várias vezes."], "Entre em uma página, volte e entre novamente.", "Se uma compra ou pagamento estiver em andamento, evite atualizar sem ler o aviso."),
    topic("Salve favoritos", "Favoritos guardam sites importantes para abrir de novo com facilidade.", "Salvar e encontrar páginas usadas com frequência.", ["Abra um site confiável.", "Clique na estrela ou opção Adicionar aos favoritos.", "Dê um nome simples.", "Escolha a pasta de favoritos.", "Abra pelo menu de favoritos depois."], "Salve um site de notícias, estudo ou serviço público que você usa.", "Revise favoritos antigos para não abrir páginas falsas por engano.", true),
    topic("Limpe dados quando necessário", "Histórico e downloads mostram páginas e arquivos acessados. Saber onde ficam ajuda na privacidade.", "Encontrar histórico, downloads e limpar dados com cuidado.", ["Abra o menu do navegador.", "Procure Histórico para ver páginas recentes.", "Procure Downloads para arquivos baixados.", "Use limpar dados apenas se souber o que será apagado.", "Feche o navegador quando terminar em computador compartilhado."], "Abra o histórico e encontre uma página visitada hoje.", "Limpar senhas salvas pode dificultar o acesso depois.")
  ]),
  makeCourse("arquivos", "computador", "Arquivos e pastas", "Organização de arquivos no computador", "Crie pastas, encontre documentos, renomeie arquivos e evite perder informações.", "PC", "#697b54", "folder", "Arquivos", [
    topic("Abra o explorador", "O explorador mostra Documentos, Downloads, Imagens, Área de Trabalho e outras pastas.", "Encontrar onde os arquivos ficam guardados.", ["Clique no ícone de pasta.", "Observe a coluna lateral.", "Abra Documentos, Downloads e Imagens.", "Use Voltar para retornar.", "Confira o nome da pasta aberta."], "Abra três pastas diferentes e diga que tipo de arquivo fica em cada uma.", "Evite alterar pastas do sistema, como Windows ou Arquivos de Programas.", true),
    topic("Crie pastas", "Pastas ajudam a separar assuntos como contas, fotos, cursos e documentos.", "Criar uma organização simples.", ["Abra Documentos.", "Clique com o botão direito em um espaço vazio.", "Escolha Novo e depois Pasta.", "Digite um nome claro.", "Pressione Enter."], "Crie uma pasta chamada Treino Digital.", "Não use nomes confusos ou muito longos."),
    topic("Renomeie arquivos", "Nomes claros facilitam encontrar comprovantes, fotos e documentos depois.", "Trocar nomes genéricos por nomes úteis.", ["Clique uma vez no arquivo.", "Clique com o botão direito.", "Escolha Renomear.", "Digite assunto e data quando fizer sentido.", "Pressione Enter."], "Renomeie um arquivo de teste para anotacoes-curso.", "Não remova extensões como .pdf, .jpg ou .docx se elas aparecerem.", true),
    topic("Faça backup", "Backup é uma cópia de segurança em outro lugar, como pendrive ou nuvem.", "Proteger arquivos importantes contra perda.", ["Escolha arquivos importantes.", "Conecte um pendrive ou abra a nuvem.", "Copie os arquivos.", "Abra o destino e confira se chegaram.", "Atualize a cópia de tempos em tempos."], "Copie um arquivo de teste para outra pasta.", "Backup no mesmo computador não protege se o aparelho quebrar.")
  ]),
  makeCourse("email", "computador", "E-mail", "Enviar, responder e organizar e-mails", "Use e-mail para mensagens, cadastros, anexos e recuperação de contas.", "PC e celular", "#8a6f2f", "keyboard", "E-mail", [
    topic("Entre no e-mail", "O e-mail é usado para mensagens, cadastros, recibos e recuperação de senhas.", "Acessar a conta de e-mail com segurança.", ["Abra o aplicativo ou site do e-mail.", "Digite seu endereço corretamente.", "Digite a senha em local privado.", "Confirme códigos se forem solicitados.", "Veja a caixa de entrada."], "Abra sua caixa de entrada e identifique remetente, assunto e data.", "Nunca informe senha completa por mensagem ou telefone.", true),
    topic("Envie uma mensagem", "Uma mensagem precisa de destinatário, assunto e texto claro.", "Escrever e enviar um e-mail simples.", ["Clique em Escrever ou Novo.", "Digite o e-mail do destinatário.", "Preencha o assunto.", "Escreva a mensagem.", "Revise antes de enviar."], "Envie um e-mail de teste para você mesmo.", "Confira o destinatário antes de enviar documentos ou informações pessoais."),
    topic("Anexe arquivos", "Anexos servem para enviar fotos, PDFs e documentos junto com o e-mail.", "Adicionar um arquivo correto à mensagem.", ["Clique no clipe ou botão Anexar.", "Escolha a pasta onde está o arquivo.", "Selecione o arquivo correto.", "Aguarde carregar.", "Confira o nome do anexo antes de enviar."], "Anexe um arquivo simples em um e-mail de teste.", "Não envie documentos pessoais para desconhecidos.", true),
    topic("Desconfie de e-mails falsos", "E-mails falsos usam urgência, prêmios, cobranças e nomes de empresas conhecidas.", "Reconhecer golpes por e-mail.", ["Observe o remetente.", "Desconfie de ameaças e prêmios.", "Não baixe anexos inesperados.", "Passe o mouse sobre links no computador para ver o endereço.", "Confirme pelo site oficial quando tiver dúvida."], "Compare um e-mail conhecido com um suspeito e observe diferenças.", "Bancos e serviços não devem pedir sua senha completa por e-mail.")
  ]),
  makeCourse("comunicacao", "celular", "Mensagens", "Mensagens, áudios e chamadas", "Use conversas, fotos, chamadas e grupos com mais segurança.", "Celular", "#3b6ea8", "chat", "Mensagens", [
    topic("Envie mensagem de texto", "Mensagens ajudam a conversar sem precisar ligar, mas é preciso conferir a conversa antes de enviar.", "Enviar uma mensagem simples para a pessoa correta.", ["Abra o aplicativo de mensagens.", "Toque no contato desejado.", "Digite uma frase curta.", "Revise texto e contato.", "Toque em enviar."], "Envie para alguém de confiança: Estou praticando o uso do celular.", "Evite enviar senhas, códigos ou dados pessoais por mensagem.", true),
    topic("Grave áudio", "Áudio é útil quando digitar é difícil ou a explicação é mais longa.", "Mandar um áudio claro e curto.", ["Abra a conversa certa.", "Procure o microfone.", "Segure ou toque conforme o aplicativo.", "Fale perto do celular.", "Envie ou cancele se não ficou bom."], "Grave um áudio de até dez segundos para alguém de confiança.", "Para assuntos importantes, confirme também por texto."),
    topic("Envie fotos com cuidado", "Fotos podem mostrar documentos, telas, pessoas e lugares. Revise antes de enviar.", "Selecionar a imagem correta e evitar exposição.", ["Abra a conversa.", "Toque no clipe, mais ou câmera.", "Escolha galeria ou câmera.", "Veja a prévia.", "Envie só se for a foto certa."], "Envie uma foto simples de um objeto para alguém de confiança.", "Não envie foto de cartão, senha anotada ou tela de banco em grupos.", true),
    topic("Controle grupos", "Grupos facilitam avisos, mas também espalham excesso de mensagens e boatos.", "Usar grupos de forma organizada.", ["Leia o nome do grupo.", "Veja quem participa.", "Silencie grupos muito movimentados.", "Responda só quando for necessário.", "Confira informações antes de encaminhar."], "Silencie um grupo por algumas horas para testar.", "Não encaminhe mensagens com ameaça, corrente ou prêmio sem verificar.")
  ]),
  makeCourse("whatsapp", "celular", "WhatsApp", "WhatsApp com segurança", "Aprenda contatos, grupos, chamadas, privacidade, bloqueio e verificação.", "Celular", "#2f8f5b", "chat", "WhatsApp", [
    topic("Encontre contatos", "Contatos salvos aparecem pelo nome, facilitando evitar números desconhecidos.", "Abrir conversas com pessoas corretas.", ["Abra o WhatsApp.", "Toque em nova conversa.", "Procure o nome da pessoa.", "Confira foto e número quando houver dúvida.", "Escreva somente depois de confirmar."], "Procure um contato de confiança sem enviar mensagem.", "Desconfie de números novos dizendo ser parentes pedindo dinheiro.", true),
    topic("Configure privacidade", "Privacidade controla foto, recado, visto por último e quem pode adicionar em grupos.", "Encontrar opções básicas de privacidade.", ["Abra Configurações.", "Toque em Privacidade.", "Revise foto do perfil e visto por último.", "Confira grupos e chamadas.", "Escolha opções mais restritas se preferir."], "Veja quem pode adicionar você a grupos.", "Quanto menos dados públicos, menor o risco de abordagem suspeita."),
    topic("Ative verificação em duas etapas", "Essa proteção dificulta que outra pessoa use sua conta indevidamente.", "Adicionar uma senha extra à conta.", ["Abra Configurações.", "Toque em Conta.", "Entre em Verificação em duas etapas.", "Crie um PIN que você consiga lembrar.", "Adicione e-mail de recuperação se possível."], "Verifique se essa opção está ativa no seu aparelho.", "Nunca compartilhe código de confirmação recebido por SMS.", true),
    topic("Bloqueie e denuncie", "Bloquear impede contato insistente, golpe ou mensagem ofensiva.", "Saber agir diante de contato abusivo.", ["Abra a conversa suspeita.", "Toque no nome ou número.", "Procure Bloquear ou Denunciar.", "Leia o aviso.", "Confirme se tiver certeza."], "Localize a opção em uma conversa sem concluir o bloqueio.", "Guarde prints em caso de ameaça ou golpe financeiro.")
  ]),
  makeCourse("redes-sociais", "celular", "Redes sociais", "Uso básico de redes sociais", "Entenda perfil, publicações, curtidas, comentários, privacidade e golpes comuns.", "Celular", "#8b5e9e", "app", "Redes sociais", [
    topic("Entenda perfil e feed", "Perfil mostra suas informações. Feed mostra publicações de pessoas, páginas e temas que você acompanha.", "Saber a diferença entre perfil, feed e publicação.", ["Abra a rede social.", "Entre no seu perfil.", "Veja foto, nome e informações públicas.", "Volte para o feed.", "Observe publicações e anúncios."], "Abra seu perfil e veja o que aparece para outras pessoas.", "Evite publicar endereço, documentos, rotina e dados de crianças.", true),
    topic("Publique com cuidado", "Uma publicação pode ser vista, salva e compartilhada por outras pessoas.", "Pensar antes de publicar texto, foto ou localização.", ["Toque em criar publicação.", "Escreva uma frase curta.", "Escolha foto apenas se quiser.", "Confira quem poderá ver.", "Publique ou descarte se mudar de ideia."], "Crie um rascunho e cancele antes de publicar.", "Não publique comprovantes, passagens, documentos ou informações bancárias."),
    topic("Comente e curta", "Curtidas e comentários são formas públicas ou semipúblicas de interação.", "Interagir sem entrar em brigas ou golpes.", ["Leia a publicação inteira.", "Curta apenas se concordar ou gostar.", "Escreva comentários respeitosos.", "Evite discutir com desconhecidos.", "Denuncie conteúdo ofensivo quando necessário."], "Encontre uma publicação educativa e observe as opções de curtir e comentar.", "Links nos comentários podem ser golpes.", true),
    topic("Ajuste privacidade", "Configurações de privacidade limitam quem vê seu conteúdo e quem pode falar com você.", "Encontrar controles de segurança da rede social.", ["Abra menu ou configurações.", "Procure Privacidade ou Segurança.", "Revise quem vê suas publicações.", "Revise mensagens de desconhecidos.", "Bloqueie perfis abusivos."], "Abra as configurações e encontre a área de privacidade.", "Perfis falsos usam fotos bonitas, urgência ou promessa de dinheiro.")
  ]),
  makeCourse("fotos", "celular", "Fotos e galeria", "Câmera, galeria e armazenamento", "Tire fotos, encontre imagens, apague excessos e evite expor arquivos pessoais.", "Celular", "#9a5f3f", "phone", "Fotos", [
    topic("Tire uma foto nítida", "Uma boa foto depende de luz, enquadramento e mão firme.", "Usar a câmera para registrar algo com clareza.", ["Abra a câmera.", "Limpe a lente se a imagem estiver embaçada.", "Aponte para o objeto.", "Toque na tela para focar.", "Aperte o botão de foto."], "Fotografe um objeto sobre a mesa com boa luz.", "Não fotografe documentos de outras pessoas sem autorização.", true),
    topic("Encontre na galeria", "A galeria guarda fotos, capturas de tela e imagens recebidas.", "Localizar imagens recentes e antigas.", ["Abra Fotos ou Galeria.", "Veja a área Recentes.", "Use álbuns quando existirem.", "Toque na foto para ampliar.", "Use voltar para retornar."], "Encontre a foto que você acabou de tirar.", "Fotos recebidas em mensagens podem aparecer misturadas com fotos pessoais."),
    topic("Apague excessos", "Apagar fotos repetidas libera espaço e facilita encontrar o que importa.", "Excluir imagens sem perder arquivos importantes.", ["Abra a galeria.", "Selecione uma foto sem importância.", "Toque na lixeira.", "Confirme a exclusão.", "Veja se existe pasta de apagados recentemente."], "Apague uma foto de teste e procure onde ela ficou temporariamente.", "Revise antes de apagar fotos de família, documentos ou comprovantes.", true),
    topic("Compartilhe com segurança", "Compartilhar fotos exige conferir imagem, destinatário e informações visíveis.", "Enviar imagens sem expor dados indevidos.", ["Abra a foto.", "Toque em compartilhar.", "Escolha o aplicativo.", "Escolha a pessoa correta.", "Confirme antes de enviar."], "Compartilhe uma imagem simples com alguém de confiança.", "Evite enviar fotos com cartão, senha, endereço ou tela de banco.")
  ]),
  makeCourse("seguranca", "celular", "Segurança digital", "Golpes, links e proteção", "Aprenda cuidados básicos para reconhecer mensagens falsas e proteger contas.", "PC e celular", "#4f7f52", "shield", "Segurança", [
    topic("Reconheça links suspeitos", "Links perigosos costumam vir com prêmio, ameaça, cobrança inesperada ou pedido de pressa.", "Identificar sinais de risco antes de clicar.", ["Leia a mensagem inteira.", "Veja se cria urgência ou medo.", "Confira quem enviou.", "Observe endereço estranho ou encurtado.", "Na dúvida, não clique."], "Analise uma mensagem antiga e procure sinais de pressa, pedido e remetente.", "Não informe senha, CPF ou banco depois de abrir link recebido por mensagem.", true),
    topic("Desconfie de pedidos urgentes", "Golpes usam pressa para impedir que a pessoa pense e confirme.", "Parar antes de enviar dinheiro ou dados.", ["Pare antes de responder.", "Leia o que estão pedindo.", "Ligue para a pessoa por número conhecido.", "Faça perguntas de confirmação.", "Peça ajuda se envolver dinheiro."], "Escreva o que você faria antes de enviar um Pix pedido por mensagem.", "Não faça pagamento apenas porque parece urgente."),
    topic("Proteja seus aparelhos", "Tela bloqueada, atualização e cuidado com aplicativos reduzem riscos.", "Criar hábitos básicos de proteção.", ["Use senha, digital ou rosto para bloquear.", "Atualize aplicativos conhecidos.", "Remova aplicativos que não usa.", "Não empreste celular desbloqueado.", "Anote contatos de apoio."], "Confira se seu celular bloqueia a tela automaticamente.", "Não instale aplicativos fora da loja oficial.", true),
    topic("Peça ajuda antes de agir", "Pedir ajuda é uma medida de segurança quando há dúvida, dinheiro ou documento envolvido.", "Saber quando interromper uma ação.", ["Pare se sentir medo ou confusão.", "Não clique em novos botões.", "Mostre a mensagem a alguém de confiança.", "Explique o que apareceu.", "Só continue se estiver claro."], "Escolha uma pessoa de confiança para dúvidas digitais.", "É melhor demorar alguns minutos do que perder conta ou dinheiro.")
  ]),
  makeCourse("senhas", "computador", "Senhas", "Senhas e recuperação de contas", "Crie senhas melhores, guarde com cuidado e recupere acesso sem cair em golpes.", "PC e celular", "#7c667d", "shield", "Senhas", [
    topic("Crie senha forte", "Uma boa senha mistura palavras, números e símbolos, sem usar dados fáceis.", "Criar senhas mais difíceis de adivinhar.", ["Evite aniversário, nome e 123456.", "Use frase ou combinação de palavras.", "Inclua números e símbolo quando possível.", "Use senhas diferentes em contas importantes.", "Teste se você consegue lembrar."], "Crie uma senha de treino sem usar dados pessoais reais.", "Não reutilize a senha do banco em redes sociais.", true),
    topic("Guarde com cuidado", "Senhas precisam ficar em local seguro e não devem ser compartilhadas.", "Escolher uma forma segura de guardar senhas.", ["Não envie senhas por mensagem.", "Evite deixar anotada junto do celular.", "Use caderno guardado se precisar anotar.", "Considere gerenciador de senhas se tiver apoio.", "Atualize senhas antigas."], "Revise onde suas senhas estão guardadas.", "Funcionários de banco, governo e lojas não devem pedir sua senha completa."),
    topic("Recupere acesso", "Recuperação costuma usar e-mail, SMS, código ou pergunta de segurança.", "Entender o processo sem entregar código a golpistas.", ["Toque em Esqueci minha senha no app ou site oficial.", "Confira para onde o código será enviado.", "Digite o código apenas no serviço oficial.", "Crie nova senha.", "Entre novamente e revise segurança."], "Localize a opção Esqueci minha senha em uma conta sem concluir o processo.", "Não passe código de recuperação para outra pessoa.", true),
    topic("Ative dupla verificação", "A segunda etapa protege mesmo quando alguém descobre a senha.", "Adicionar camada extra em contas importantes.", ["Abra configurações da conta.", "Procure Segurança.", "Escolha Duas etapas ou Autenticação em dois fatores.", "Escolha app, SMS ou e-mail se disponível.", "Guarde códigos de recuperação."], "Verifique se e-mail ou rede social tem essa opção.", "Nunca compartilhe códigos de autenticação.")
  ]),
  makeCourse("bancos", "celular", "Banco pelo celular", "Banco digital com cuidado", "Consulte saldo, salve comprovantes e reconheça situações suspeitas no aplicativo bancário.", "Celular", "#6f507a", "bank", "Banco", [
    topic("Abra o app correto", "O acesso ao banco deve começar pelo aplicativo oficial, não por links recebidos.", "Identificar e abrir o aplicativo verdadeiro do banco.", ["Procure o ícone do banco.", "Confira nome e aparência.", "Evite links por SMS ou mensagem.", "Instale apenas pela loja oficial.", "Mantenha o app atualizado."], "Localize o aplicativo do seu banco e coloque em área fácil de encontrar.", "Golpistas imitam avisos de banco para roubar dados.", true),
    topic("Entre com privacidade", "Senha, digital, rosto e códigos devem ser usados sem outras pessoas vendo.", "Acessar o banco protegendo credenciais.", ["Sente-se em local seguro.", "Confira se ninguém observa a tela.", "Digite senha com calma.", "Não aceite ajuda de desconhecidos.", "Leia mensagens de erro antes de tentar de novo."], "Abra o app até a tela inicial sem fazer transação.", "Nunca informe senha, token ou código recebido por SMS."),
    topic("Consulte saldo e extrato", "Saldo mostra o valor disponível. Extrato mostra entradas, saídas e compras.", "Conferir movimentações recentes.", ["Entre no aplicativo.", "Procure Saldo ou Conta.", "Abra Extrato ou Movimentações.", "Toque em uma operação para detalhes.", "Anote apenas se necessário e seguro."], "Confira as últimas três movimentações e veja se reconhece todas.", "Se aparecer algo desconhecido, fale com o banco pelos canais oficiais.", true),
    topic("Salve comprovantes", "Comprovantes registram Pix, pagamentos e transferências.", "Guardar comprovantes sem expor dados.", ["Depois da operação, toque em Ver comprovante.", "Use Salvar, Baixar ou Compartilhar.", "Veja se foi para Downloads ou Galeria.", "Envie apenas para quem precisa.", "Organize comprovantes importantes."], "Abra um comprovante antigo e localize as opções disponíveis.", "Não publique comprovantes em grupos ou redes sociais.")
  ]),
  makeCourse("pix", "celular", "Pix", "Pix, transferências e comprovantes", "Entenda chave Pix, QR Code, conferência de dados e cuidados antes de pagar.", "Celular", "#2e7d7b", "bank", "Pix", [
    topic("Entenda a chave Pix", "Chave Pix pode ser CPF, telefone, e-mail ou chave aleatória usada para localizar uma conta.", "Saber o que é chave Pix e quando usá-la.", ["Abra a área Pix do banco.", "Leia as opções disponíveis.", "Veja suas chaves cadastradas se houver.", "Para pagar, digite ou cole a chave recebida.", "Confira os dados antes de continuar."], "Abra a área Pix sem fazer pagamento e veja as opções.", "Não envie CPF ou telefone para desconhecidos sem necessidade.", true),
    topic("Confira antes de pagar", "A conferência evita enviar dinheiro para pessoa errada ou golpista.", "Criar rotina de verificação antes do envio.", ["Digite chave, valor e descrição.", "Confira nome de quem vai receber.", "Confira banco e parte do CPF se aparecer.", "Leia o valor em voz baixa.", "Só confirme se tudo estiver correto."], "Simule mentalmente quais dados você conferiria antes de pagar.", "Pix geralmente não pode ser desfeito pelo usuário depois de enviado."),
    topic("Use QR Code com atenção", "QR Code pode facilitar pagamentos, mas precisa vir de fonte confiável.", "Ler QR Code sem cair em cobrança falsa.", ["Abra a opção Pix com QR Code.", "Aponte a câmera para o código.", "Espere aparecer os dados.", "Confira recebedor e valor.", "Confirme apenas se reconhecer."], "Localize no app onde fica pagar por QR Code.", "Desconfie de QR Code colado por cima de outro em locais públicos.", true),
    topic("Guarde o comprovante", "O comprovante prova que a operação foi feita e ajuda em conferências.", "Salvar e encontrar comprovantes de Pix.", ["Após enviar, toque em comprovante.", "Salve ou compartilhe se necessário.", "Confira pasta Downloads ou Galeria.", "Nomeie ou organize quando possível.", "Mantenha registros importantes."], "Procure um comprovante antigo no aplicativo.", "Comprovante contém dados pessoais. Compartilhe somente com quem precisa.")
  ]),
  makeCourse("compras-online", "celular", "Compras online", "Comprar pela internet com cuidado", "Pesquise lojas, compare preços, entenda frete, pagamento, entrega e troca.", "PC e celular", "#ad6b3a", "cart", "Compras", [
    topic("Pesquise a loja", "Antes de comprar, confira se a loja existe, tem reputação e canais de atendimento.", "Avaliar se um vendedor parece confiável.", ["Pesquise o nome da loja.", "Leia avaliações e reclamações.", "Confira endereço do site.", "Procure CNPJ ou contato.", "Compare com lojas conhecidas."], "Pesquise uma loja sem comprar e veja o que outras pessoas dizem.", "Preço muito abaixo do normal pode indicar golpe.", true),
    topic("Compare produto e frete", "O preço final inclui produto, frete, prazo e possíveis taxas.", "Evitar surpresa no valor final.", ["Leia nome e descrição do produto.", "Confira tamanho, cor, modelo e quantidade.", "Veja prazo de entrega.", "Some frete e valor do produto.", "Revise antes de finalizar."], "Compare o mesmo produto em duas lojas diferentes.", "Não compre com pressa por anúncio de promoção relâmpago."),
    topic("Escolha pagamento seguro", "Cartão, boleto e Pix têm cuidados diferentes.", "Entender riscos de cada forma de pagamento.", ["Prefira lojas conhecidas.", "Confira se o site é o correto.", "Evite Pix para pessoa física desconhecida.", "Guarde confirmação de pagamento.", "Use cartão virtual se souber configurar."], "Veja quais formas de pagamento uma loja confiável oferece.", "Nunca envie foto do cartão por mensagem.", true),
    topic("Acompanhe a entrega", "Depois da compra, acompanhe pedido, nota, código de rastreio e prazo.", "Monitorar a compra até receber.", ["Veja e-mail ou área Meus pedidos.", "Anote número do pedido.", "Acompanhe rastreio quando houver.", "Confira produto ao receber.", "Guarde nota e comprovantes."], "Abra uma compra antiga e veja se ainda há detalhes do pedido.", "Cuidado com mensagem falsa de taxa extra de entrega.")
  ]),
  makeCourse("govbr", "computador", "gov.br", "Serviços públicos digitais", "Use conta gov.br, agendamentos, documentos, INSS, Receita e outros serviços com segurança.", "PC e celular", "#4e6f91", "shield", "gov.br", [
    topic("Entenda a conta gov.br", "A conta gov.br dá acesso a serviços públicos digitais usando CPF e senha.", "Saber para que serve a conta gov.br.", ["Acesse o site ou app oficial gov.br.", "Digite CPF apenas no endereço oficial.", "Entre com senha se já tiver conta.", "Confira seu nível de segurança.", "Procure o serviço desejado."], "Abra o endereço oficial gov.br e observe as opções sem informar dados se estiver inseguro.", "Não entre em gov.br por link recebido de desconhecidos.", true),
    topic("Use serviços oficiais", "Serviços públicos podem permitir consultas, agendamentos, documentos e solicitações.", "Encontrar serviços sem cair em intermediários falsos.", ["Procure o serviço pelo nome.", "Confira se está dentro do domínio oficial.", "Leia requisitos antes de iniciar.", "Separe documentos necessários.", "Salve protocolos gerados."], "Pesquise um serviço público e identifique se o site é oficial.", "Desconfie de sites cobrando por serviço gratuito do governo."),
    topic("Guarde protocolos", "Protocolos comprovam atendimento, solicitação ou agendamento.", "Registrar informações importantes.", ["Ao finalizar um serviço, procure número de protocolo.", "Salve PDF ou tire print se for adequado.", "Anote data e nome do serviço.", "Guarde em pasta de documentos.", "Verifique prazo de retorno."], "Crie uma pasta para guardar protocolos e comprovantes digitais.", "Não compartilhe protocolos com desconhecidos se tiverem dados pessoais.", true),
    topic("Recupere acesso com cuidado", "Recuperação pode envolver e-mail, SMS, banco ou reconhecimento facial.", "Recuperar conta usando somente canais oficiais.", ["Entre pelo site ou app oficial.", "Toque em Esqueci minha senha.", "Escolha uma opção disponível.", "Digite códigos apenas no gov.br.", "Crie nova senha e guarde com cuidado."], "Localize a opção de recuperação sem concluir se não precisar.", "Não pague pessoas desconhecidas para recuperar sua conta.")
  ]),
  makeCourse("documentos", "computador", "Documentos digitais", "PDF, impressão e digitalização", "Abra, salve, compartilhe, digitalize e imprima documentos importantes.", "PC e celular", "#667a90", "folder", "Documentos", [
    topic("Abra PDFs", "PDF é um formato comum para boletos, comprovantes, contratos e documentos.", "Abrir e conferir um arquivo PDF.", ["Localize o arquivo.", "Dê dois cliques ou toque nele.", "Aguarde abrir no leitor ou navegador.", "Use zoom para ler melhor.", "Feche quando terminar."], "Abra um PDF confiável e encontre título, data e número de páginas.", "Não abra anexos inesperados de remetentes desconhecidos.", true),
    topic("Digitalize pelo celular", "Digitalizar transforma papel em imagem ou PDF para enviar e guardar.", "Criar cópia digital legível.", ["Coloque o documento em local iluminado.", "Abra câmera ou app de digitalização.", "Enquadre o documento inteiro.", "Tire a foto ou escaneie.", "Salve com nome claro."], "Digitalize um papel sem dados pessoais para treinar.", "Guarde documentos pessoais em local seguro, não em grupos."),
    topic("Imprima quando precisar", "Impressão ainda é útil para comprovantes, formulários e documentos.", "Enviar arquivo para impressão.", ["Abra o documento.", "Clique em Imprimir.", "Escolha a impressora correta.", "Confira páginas e quantidade.", "Clique em Imprimir."], "Abra a tela de impressão de um documento de teste e cancele antes de imprimir.", "Confira se não está imprimindo páginas demais.", true),
    topic("Compartilhe documentos", "Documentos podem conter CPF, endereço, assinatura e dados sensíveis.", "Enviar documentos somente para destinatário correto.", ["Confira qual documento será enviado.", "Revise o destinatário.", "Use canais oficiais quando possível.", "Evite grupos.", "Apague cópias desnecessárias depois."], "Organize documentos importantes em uma pasta própria.", "Nunca mande documento para proposta suspeita de prêmio, empréstimo ou vaga falsa.")
  ]),
  makeCourse("mapas", "celular", "Mapas e localização", "Rotas, endereços e transporte", "Pesquise endereços, escolha rotas, compartilhe localização e use transporte com atenção.", "Celular", "#7a6250", "map", "Mapas", [
    topic("Pesquise endereço", "Mapas ajudam a encontrar ruas, lojas, serviços e trajetos.", "Buscar um local corretamente.", ["Abra o app de mapas.", "Toque no campo de busca.", "Digite nome ou endereço.", "Confira cidade e bairro.", "Toque no resultado correto."], "Pesquise um local conhecido da sua cidade.", "Confirme endereço em mais de uma fonte quando for consulta importante.", true),
    topic("Escolha rota", "Rotas podem ser para carro, transporte público, caminhada ou aplicativo de transporte.", "Ver opções de caminho e tempo.", ["Com o local aberto, toque em Rotas.", "Escolha meio de transporte.", "Veja tempo estimado.", "Observe distância e alternativas.", "Inicie apenas quando estiver pronto."], "Compare uma rota de carro e uma de caminhada.", "Não manuseie o celular enquanto dirige."),
    topic("Compartilhe localização", "Compartilhar localização ajuda encontros e segurança, mas deve ser feito com pessoas confiáveis.", "Enviar localização com controle.", ["Abra o app de mensagens ou mapas.", "Escolha compartilhar localização.", "Selecione pessoa de confiança.", "Escolha tempo se for localização em tempo real.", "Pare o compartilhamento quando não precisar."], "Localize onde fica a opção sem enviar de verdade.", "Não compartilhe localização em grupos públicos.", true),
    topic("Use transporte com atenção", "Aplicativos de transporte mostram motorista, placa, rota e valor estimado.", "Conferir dados antes de entrar no veículo.", ["Peça a corrida no app.", "Confira placa e modelo.", "Confira nome do motorista.", "Pergunte o nome do passageiro antes de entrar.", "Acompanhe a rota."], "Veja em uma corrida antiga quais dados aparecem.", "Não aceite corrida fora do aplicativo.")
  ]),
  makeCourse("manutencao", "computador", "Cuidados com aparelho", "Manutenção básica e solução de problemas", "Limpeza, bateria, espaço, travamentos, reinício e quando pedir ajuda.", "PC e celular", "#62715f", "monitor", "Cuidados", [
    topic("Limpe com segurança", "Limpeza simples evita sujeira, mas líquidos e força podem danificar aparelhos.", "Limpar tela, teclado e celular sem risco.", ["Desligue o aparelho quando possível.", "Use pano macio e seco ou levemente umedecido.", "Evite jogar líquido direto.", "Limpe entradas com cuidado.", "Espere secar antes de ligar."], "Limpe a tela com pano adequado.", "Não use produtos fortes ou água diretamente no aparelho.", true),
    topic("Libere espaço", "Aparelhos cheios ficam lentos e podem impedir fotos, atualizações e downloads.", "Identificar e remover excesso.", ["Abra configurações de armazenamento.", "Veja fotos, aplicativos e downloads.", "Apague arquivos de teste e duplicados.", "Remova apps que não usa.", "Esvazie lixeira quando tiver certeza."], "Veja quanto espaço livre existe no seu aparelho.", "Não apague arquivos que você não reconhece sem orientação."),
    topic("Reinicie quando travar", "Reiniciar resolve muitos problemas simples de lentidão e aplicativos parados.", "Usar reinício antes de medidas mais arriscadas.", ["Salve o que estiver aberto.", "Pressione botão de energia.", "Escolha Reiniciar.", "Aguarde ligar novamente.", "Teste o que estava com problema."], "Reinicie o aparelho em um momento tranquilo.", "Não reinicie durante atualização ou pagamento.", true),
    topic("Peça suporte", "Alguns problemas precisam de assistência técnica ou pessoa experiente.", "Saber quando parar e pedir ajuda.", ["Anote o que aconteceu.", "Tire foto da mensagem de erro se possível.", "Não aceite acesso remoto de desconhecidos.", "Procure assistência confiável.", "Faça backup antes de reparos."], "Liste duas pessoas ou locais confiáveis para pedir ajuda.", "Golpistas fingem suporte técnico para controlar seu aparelho.")
  ]),
  makeCourse("acessibilidade", "celular", "Acessibilidade", "Aumentar letras e facilitar o uso", "Configure tamanho de texto, brilho, volume, contraste e recursos de apoio.", "PC e celular", "#7a6f50", "phone", "Acessibilidade", [
    topic("Aumente a letra", "Letras maiores ajudam a ler mensagens, menus e páginas com menos esforço.", "Alterar tamanho do texto.", ["Abra Configurações.", "Procure Tela ou Acessibilidade.", "Entre em Tamanho da fonte.", "Ajuste o controle.", "Veja se ficou confortável."], "Aumente um pouco a fonte e abra uma mensagem para comparar.", "Fonte muito grande pode esconder partes de alguns botões.", true),
    topic("Ajuste brilho e contraste", "Brilho correto melhora leitura e economiza bateria.", "Configurar tela para enxergar melhor.", ["Puxe os atalhos rápidos.", "Ajuste a barra de brilho.", "Teste em local claro e escuro.", "Procure modo escuro se preferir.", "Use contraste alto se estiver disponível."], "Mude o brilho e veja qual nível fica confortável.", "Brilho muito alto pode cansar os olhos e gastar bateria."),
    topic("Controle volume", "Volume de toque, mídia e chamada podem ser diferentes.", "Ajustar som conforme a necessidade.", ["Use botões laterais de volume.", "Abra Configurações de som.", "Veja volume de toque, mídia e alarme.", "Teste um som curto.", "Ative vibração se ajudar."], "Ajuste o volume de toque e depois o de mídia.", "Cuidado para não deixar alarme ou chamada sem som sem perceber.", true),
    topic("Use recursos de apoio", "Leitor de tela, legenda, lupa e ditado podem facilitar o uso.", "Conhecer opções de acessibilidade.", ["Abra Configurações.", "Entre em Acessibilidade.", "Leia as opções disponíveis.", "Ative apenas uma opção por vez para testar.", "Desative se atrapalhar."], "Localize acessibilidade no aparelho e veja três recursos disponíveis.", "Alguns recursos mudam gestos de navegação; teste com calma.")
  ])
];
